title: <Kaitlin Neville> # your name (or website title) here
logo: "/images/new_logo?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in Systems Engineering 
  <br><br>
  Department of Mechanical and Industrial Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/kaitlin-neville-b529a5179//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


